spring.application.name=hypermax

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/hypermax_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

#spring.main.allow-circular-references=true

spring.mail.host=smtp.gmail.com
spring.mail.username=pfemounirsaid@gmail.com
spring.mail.password=rzpqlsiiafvrlqgt
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Brave Search API
brave.api.key=BSAlWYuWdN5MyG1PZvnByvn-fjNJ5Ef
brave.api.url=https://api.search.brave.com/res/v1
brave.api.result-limit=10

# MCP Storage
mcp.storage.path=./mcp-storage
mcp.storage.filename=search_results.txt



