spring.application.name=hypermax


# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Brave Search API
brave.api.key=BSAlWYuWdN5MyG1PZvnByvn-fjNJ5Ef
brave.api.url=https://api.search.brave.com/res/v1
brave.api.result-limit=10

# MCP Storage
mcp.storage.path=./mcp-storage
mcp.storage.filename=search_results.txt
